version: "3.8"
services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - landingpage
    depends_on:
      - landingpage

  landingpage:
    image: "ghcr.io/coronatorid/landingpage/web:${TAG}"
